version: '3.8'

services:
  mysql:
    image: mysql
    container_name: meu-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SistemaGestaoHospital
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
